[experiment]
name = "bandgap-sweep"
seed = 42            # Log to neptune
local_save = false
verbose = 1

[logging]
enabled = true
name = "BGSWEEP"
project = "gongjiawei105/PVSK-ML"
api_token = "${NEPTUNE_API_TOKEN}"
group_tags = ["bandgap"]
tags = ["xgboost", "sweep"]

[hyperparameters]
n_trials = 100
direction = "minimize"
study_name = "bandgap_opt"

[data]
target_feature = "E_g"
path = "data/processed/element-composition_band-gap.parquet"


[process]
# [[process.numerical]]
# type = "scale"
# method = "normalize"

[model]
model_type = "xgboost"
n_estimators = { type = "int", low = 100, high = 1000}
max_depth = { type = "int", low = 3, high = 12 }
learning_rate = { type = "float", low = 0.01, high = 0.3 }
subsample = { type = "float", low = 0.5, high = 1.0}
min_child_weight = { type = "int", low = 1, high = 10}
colsample_bytree = { type = "float", low = 0.5, high = 1.0}
gamma = { type = "float", low = 0.0, high = 0.5}

verbose = false

